#!/bin/bash
# Written by skiqqy
# Usage: stream -h

args=( $@ ) # I want splitting
version=alpha-1.0v

usage ()
{
	cat << EOF
Stream $version ~ The simple stream utility

Usage: stream [options] [url]

options
-------

-h    Shows this message.

Written by skiqqy
EOF
	exit "$1"
}

# Play a stream
# Usage play "$url"
play ()
{
	mpv --ytdl-raw-options=force-ipv4= "$1" --no-video --input-ipc-server=/tmp/mpvsoc
}

main ()
{
	opts="h"
	while getopts "$opts" opt
	do
		case "$opt" in
			h)
				usage 0
				;;
			*)
				usage 1
				;;
		esac
	done

	echo "Stream instance ID: $$"
	play https://www.youtube.com/watch?v=5qap5aO4i9A # Just for now.
}

main "$@"
